<font color="blue" size="6">Random Sampling and Shuffling</font>

<font color ="green"><b>Random Sampling: Select a small portion of large data set</b></font>
<p>1.Building a machine learning model: Take a small portion of data set. Build a model .Fine tune it .Apply for entire data set
<p>2.Random Forest: It uses bootstrap sampling internally when it is actually training your model. Boots strap can be used for sampling intervals also
<p>3.Cross validation: Training Set and Testing Set

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('DATASETS\\hungary_chickenpox.csv')

In [3]:
df

,Date,BUDAPEST,BARANYA,BACS,BEKES,BORSOD,CSONGRAD,FEJER,GYOR,HAJDU,...,JASZ,KOMAROM,NOGRAD,PEST,SOMOGY,SZABOLCS,TOLNA,VAS,VESZPREM,ZALA
0,03/01/2005,168,79,30,173,169,42,136,120,162,...,130,57,2,178,66,64,11,29,87,68
1,10/01/2005,157,60,30,92,200,53,51,70,84,...,80,50,29,141,48,29,58,53,68,26
2,17/01/2005,96,44,31,86,93,30,93,84,191,...,64,46,4,157,33,33,24,18,62,44
3,24/01/2005,163,49,43,126,46,39,52,114,107,...,63,54,14,107,66,50,25,21,43,31
4,31/01/2005,122,78,53,87,103,34,95,131,172,...,61,49,11,124,63,56,7,47,85,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,01/12/2014,95,12,41,6,39,0,16,15,14,...,56,7,13,122,4,23,4,11,110,10
518,08/12/2014,43,39,31,10,34,3,2,30,25,...,34,20,18,70,36,5,23,22,63,9
519,15/12/2014,35,7,15,0,0,0,7,7,4,...,30,36,4,72,5,21,14,0,17,10
520,22/12/2014,30,23,8,0,11,4,1,9,10,...,27,17,21,12,5,17,1,1,83,2
521,29/12/2014,259,42,49,32,38,15,11,98,61,...,112,61,53,256,45,39,27,11,103,25

In [4]:
nrows=round(df.shape[0]*.7)

In [5]:
nrows

365

In [6]:
#replace=False rows once picked will not be picked again ,
#random_state=100 is for pseudo randomness same set of data is picked again 
df.sample=df.sample(nrows,replace=False,random_state=100)
df.sample

,Date,BUDAPEST,BARANYA,BACS,BEKES,BORSOD,CSONGRAD,FEJER,GYOR,HAJDU,...,JASZ,KOMAROM,NOGRAD,PEST,SOMOGY,SZABOLCS,TOLNA,VAS,VESZPREM,ZALA
304,01/11/2010,73,16,2,12,7,8,7,3,15,...,43,18,8,58,20,3,3,23,8,29
332,16/05/2011,128,55,101,31,109,95,71,52,69,...,57,47,35,152,31,100,7,2,100,40
78,03/07/2006,236,70,25,5,50,27,22,118,72,...,23,41,14,89,19,37,26,24,34,26
380,16/04/2012,180,27,90,15,134,39,79,76,41,...,27,23,20,107,38,67,13,43,52,21
516,24/11/2014,16,15,14,2,3,0,9,23,6,...,24,2,9,25,16,0,9,3,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
366,09/01/2012,291,41,86,11,248,20,101,64,72,...,39,27,38,118,41,13,3,50,30,23
519,15/12/2014,35,7,15,0,0,0,7,7,4,...,30,36,4,72,5,21,14,0,17,10
34,29/08/2005,15,1,2,1,2,3,1,7,6,...,5,5,0,13,2,4,1,0,0,2
346,22/08/2011,14,1,1,2,5,23,2,3,12,...,3,3,1,7,0,9,1,5,5,1
144,08/10/2007,14,13,12,12,38,6,16,13,15,...,3,15,7,34,2,55,8,2,3,6

<font color="green" size="4"><b>Bootstrap Sampling:</b></font>
<p>Bootstrap sampling is when you pick the same number of rows as in the dataset but with replacement.
<p>Used In:
<p>1.In machine learning algorithms such as Random Forest,Bagging
<p>2.Computing confidence intervals

In [9]:
df = pd.read_csv('DATASETS\\hungary_chickenpox.csv')

In [10]:
#frac – a float value representing the fraction of random axis items (rows or columns) to return. 
#By default, the method returns 1/N items (virtually meaning a single item), 
#where N is the overall number of items. 
#This parameter can't be used in combination with the n parameter.
df.sample(frac=1,replace=True,random_state=100)

,Date,BUDAPEST,BARANYA,BACS,BEKES,BORSOD,CSONGRAD,FEJER,GYOR,HAJDU,...,JASZ,KOMAROM,NOGRAD,PEST,SOMOGY,SZABOLCS,TOLNA,VAS,VESZPREM,ZALA
520,22/12/2014,30,23,8,0,11,4,1,9,10,...,27,17,21,12,5,17,1,1,83,2
79,10/07/2006,111,21,25,6,28,32,8,24,17,...,24,15,5,49,7,17,11,9,7,20
350,19/09/2011,4,3,1,2,8,3,1,3,0,...,3,3,10,6,0,6,3,5,2,6
53,09/01/2006,189,56,46,15,92,100,27,31,51,...,65,55,48,102,49,30,53,72,110,67
280,17/05/2010,185,102,160,25,65,17,65,85,68,...,37,95,20,216,27,3,15,29,99,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,02/08/2010,24,3,3,2,6,6,3,10,4,...,7,3,3,7,2,1,7,0,5,6
379,09/04/2012,68,14,50,2,8,48,41,140,50,...,14,16,22,91,17,27,10,35,24,26
483,07/04/2014,82,21,157,26,109,61,41,62,87,...,66,5,46,80,14,54,12,54,54,20
27,11/07/2005,110,15,67,13,36,20,24,41,49,...,58,43,12,31,11,35,8,18,39,14
491,02/06/2014,235,17,85,27,158,72,20,33,36,...,86,27,16,85,6,11,19,22,13,38

In [11]:
df.sample(frac=0.01,replace=True,random_state=100)

,Date,BUDAPEST,BARANYA,BACS,BEKES,BORSOD,CSONGRAD,FEJER,GYOR,HAJDU,...,JASZ,KOMAROM,NOGRAD,PEST,SOMOGY,SZABOLCS,TOLNA,VAS,VESZPREM,ZALA
520,22/12/2014,30,23,8,0,11,4,1,9,10,...,27,17,21,12,5,17,1,1,83,2
79,10/07/2006,111,21,25,6,28,32,8,24,17,...,24,15,5,49,7,17,11,9,7,20
350,19/09/2011,4,3,1,2,8,3,1,3,0,...,3,3,10,6,0,6,3,5,2,6
53,09/01/2006,189,56,46,15,92,100,27,31,51,...,65,55,48,102,49,30,53,72,110,67
280,17/05/2010,185,102,160,25,65,17,65,85,68,...,37,95,20,216,27,3,15,29,99,11

In [12]:
df.sample(frac=0.10,replace=True,random_state=100)

,Date,BUDAPEST,BARANYA,BACS,BEKES,BORSOD,CSONGRAD,FEJER,GYOR,HAJDU,...,JASZ,KOMAROM,NOGRAD,PEST,SOMOGY,SZABOLCS,TOLNA,VAS,VESZPREM,ZALA
520,22/12/2014,30,23,8,0,11,4,1,9,10,...,27,17,21,12,5,17,1,1,83,2
79,10/07/2006,111,21,25,6,28,32,8,24,17,...,24,15,5,49,7,17,11,9,7,20
350,19/09/2011,4,3,1,2,8,3,1,3,0,...,3,3,10,6,0,6,3,5,2,6
53,09/01/2006,189,56,46,15,92,100,27,31,51,...,65,55,48,102,49,30,53,72,110,67
280,17/05/2010,185,102,160,25,65,17,65,85,68,...,37,95,20,216,27,3,15,29,99,11
228,18/05/2009,198,47,46,68,69,38,49,48,149,...,109,42,21,100,34,43,21,135,18,43
316,24/01/2011,208,51,28,34,65,65,22,86,34,...,107,39,9,93,22,52,38,50,70,41
507,22/09/2014,16,4,1,1,2,7,3,5,3,...,6,3,0,8,1,1,0,4,7,1
93,16/10/2006,20,4,9,6,24,11,7,7,16,...,27,4,4,29,8,24,2,1,4,4
86,28/08/2006,41,1,0,2,2,6,2,2,2,...,0,0,2,17,2,2,0,0,3,2
386,28/05/2012,93,2,43,8,150,9,60,82,51,...,14,7,14,131,56,36,10,18,36,10
415,17/12/2012,192,37,18,22,122,8,19,20,58,...,13,1,13,90,17,15,20,3,21,1
141,17/09/2007,6,4,2,1,5,0,5,3,3,...,0,2,3,6,0,1,4,0,0,1
4,31/01/2005,122,78,53,87,103,34,95,131,172,...,61,49,11,124,63,56,7,47,85,60
135,06/08/2007,7,4,5,2,7,3,0,33,2,...,2,2,1,7,1,9,2,0,5,0
49,12/12/2005,106,32,77,6,91,37,30,38,11,...,51,31,28,133,23,38,35,89,97,47
431,08/04/2013,235,27,21,13,109,8,23,47,114,...,55,35,28,168,44,32,102,38,62,2
317,31/01/2011,174,31,23,76,61,24,20,57,28,...,67,24,11,108,15,40,8,27,60,43
336,13/06/2011,120,38,46,47,64,52,42,19,38,...,43,23,20,68,16,48,34,9,60,19
2,17/01/2005,96,44,31,86,93,30,93,84,191,...,64,46,4,157,33,33,24,18,62,44
478,03/03/2014,99,53,51,41,103,61,78,52,39,...,23,0,28,77,22,1,25,21,31,2
403,24/09/2012,8,2,0,2,5,0,0,8,1,...,0,3,1,5,1,2,2,1,2,0
63,20/03/2006,193,78,109,35,82,91,44,87,48,...,137,34,52,160,70,31,96,110,210,39
181,23/06/2008,51,35,34,11,69,43,45,43,53,...,43,58,8,93,28,13,31,20,25,10
283,07/06/2010,150,74,94,8,48,36,46,70,49,...,120,52,17,205,55,3,39,9,102,13
238,27/07/2009,18,24,4,19,21,4,13,7,12,...,6,6,2,29,2,1,14,4,5,4
369,30/01/2012,147,18,61,8,58,53,63,38,32,...,26,24,30,96,47,15,6,31,32,12
303,25/10/2010,95,43,30,45,22,8,4,0,3,...,45,11,1,56,63,5,16,9,15,60
172,21/04/2008,117,60,134,47,101,90,164,106,62,...,80,14,39,115,57,46,52,10,54,14
274,05/04/2010,160,80,108,17,52,11,34,75,54,...,52,52,11,143,23,22,35,17,39,6
192,08/09/2008,3,0,8,2,4,0,1,0,3,...,1,0,0,4,3,1,0,9,3,5
437,20/05/2013,187,44,46,5,52,64,40,46,48,...,37,19,49,133,13,38,59,38,24,13
273,29/03/2010,121,112,88,11,85,55,63,93,108,...,58,55,26,148,36,30,59,13,57,16
30,01/08/2005,37,4,21,1,6,6,9,9,18,...,18,17,2,19,5,11,4,6,17,2
17,02/05/2005,98,66,81,86,48,40,59,131,111,...,97,64,27,83,42,29,2,42,39,32
53,09/01/2006,189,56,46,15,92,100,27,31,51,...,65,55,48,102,49,30,53,72,110,67
68,24/04/2006,268,139,97,44,97,165,103,76,34,...,104,54,37,221,81,95,82,71,190,22
488,12/05/2014,391,35,274,62,109,20,42,87,165,...,136,37,84,125,1,56,56,37,34,13
347,29/08/2011,13,0,1,1,10,2,0,3,1,...,0,1,0,3,1,1,0,1,6,4
475,10/02/2014,59,31,1,26,76,77,18,66,38,...,14,17,27,68,20,34,3,24,38,14
0,03/01/2005,168,79,30,173,169,42,136,120,162,...,130,57,2,178,66,64,11,29,87,68
13,04/04/2005,132,83,59,130,152,54,78,128,207,...,138,66,6,121,41,92,8,52,108,38
185,21/07/2008,21,17,10,7,18,11,3,12,4,...,91,18,11,3,9,10,6,12,11,1
460,28/10/2013,21,9,1,11,13,28,8,10,33,...,18,6,1,12,46,30,1,0,18,5
362,12/12/2011,91,40,86,19,31,15,40,50,17,...,25,20,58,100,22,41,8,30,20,12
131,09/07/2007,99,21,16,27,33,3,6,27,33,...,8,10,11,30,9,14,11,3,19,0
212,26/01/2009,176,62,44,53,100,46,5,56,67,...,65,27,65,107,54,74,13,42,61,23
394,23/07/2012,65,2,11,9,19,3,2,6,24,...,1,2,1,24,7,9,0,27,10,1
215,16/02/2009,188,47,64,57,74,77,8,45,97,...,86,46,45,142,87,39,44,45,43,6
502,18/08/2014,6,4,1,1,0,34,6,3,2,...,10,0,2,10,1,1,0,0,8,3
495,30/06/2014,111,19,25,4,7,31,15,28,12,...,46,2,8,61,1,11,20,10,6,0
176,19/05/2008,211,103,70,59,91,109,98,98,86,...,58,72,42,85,97,23,34,9,82,14